### ISSUE TITLE
Add support for new "buffer overrun" compatibility mode, VMC and custom games location for USB via List Builder GUI

### ISSUE THREAD

**Issue by 10522** [sync-on-luma/xebplus-neutrino-loader-plugin#15]
@sync-on-luma @MegaBitmap can you please implement this?

**Comment by sync-on-luma** [comment]
The buffer overrun flag is currently only present in the development build of neutrino. This plugin is designed around the stable build. A buffer overrun setting will be added if/when that feature makes it's way to the stable release.

VMC is being worked on.

What propose would setting a custom path for USB games serve? The XEBPLUS folder must be on the same drive as the games in order to function, and the plugin is hard-coded to load from the root directory of all devices. Setting the USB games location to any path other than the default would prevent the plugin from working.

**Comment by MegaBitmap** [comment]
@10522 you should do what I did, create a fork and then add whatever features you want.

**Comment by sync-on-luma** [comment]
Closing this issue, as VMC support is now in the main release and other questions have been answered.
